# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiXXprogressbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from random import randint
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsScene, QApplication, QFileDialog, QMainWindow, QPushButton, QMessageBox
from PyQt5.QtGui import QPixmap

import cv2
import os
from finalEncryption import *
import time


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 605)
        MainWindow.setFixedSize(912, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.encGraphicsView = QtWidgets.QGraphicsView(self.tab_2)
        self.encGraphicsView.setGeometry(QtCore.QRect(10, 10, 421, 371))
        self.encGraphicsView.setObjectName("encGraphicsView")
        self.encGraphicsView2 = QtWidgets.QGraphicsView(self.tab_2)
        self.encGraphicsView2.setGeometry(QtCore.QRect(450, 10, 421, 371))
        self.encGraphicsView2.setObjectName("encGraphicsView2")
        self.encOpenBtn = QtWidgets.QPushButton(self.tab_2)
        self.encOpenBtn.setGeometry(QtCore.QRect(10, 400, 93, 28))
        self.encOpenBtn.setObjectName("encOpenBtn")
        self.encKeyPlayfair = QtWidgets.QLineEdit(self.tab_2)
        self.encKeyPlayfair.setGeometry(QtCore.QRect(130, 400, 301, 21))
        self.encKeyPlayfair.setObjectName("encKeyPlayfair")
        self.encPrimeLE1 = QtWidgets.QLineEdit(self.tab_2)
        self.encPrimeLE1.setGeometry(QtCore.QRect(130, 430, 141, 22))
        self.encPrimeLE1.setObjectName("encPrimeLE1")
        self.encPrimeLE2 = QtWidgets.QLineEdit(self.tab_2)
        self.encPrimeLE2.setGeometry(QtCore.QRect(290, 430, 141, 22))
        self.encPrimeLE2.setObjectName("encPrimeLE2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(460, 400, 81, 16))
        self.label.setObjectName("label")
        self.encKeyPublic = QtWidgets.QLineEdit(self.tab_2)
        self.encKeyPublic.setGeometry(QtCore.QRect(130, 460, 141, 22))
        self.encKeyPublic.setObjectName("encKeyPublic")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(460, 430, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(460, 460, 91, 16))
        self.label_3.setObjectName("label_3")
        self.encBtn = QtWidgets.QPushButton(self.tab_2)
        self.encBtn.setGeometry(QtCore.QRect(130, 500, 93, 28))
        self.encBtn.setObjectName("encBtn")
        self.encTimeLbl = QtWidgets.QLabel(self.tab_2)
        self.encTimeLbl.setGeometry(QtCore.QRect(550, 400, 141, 16))
        self.encTimeLbl.setText("")
        self.encTimeLbl.setObjectName("encTimeLbl")
        self.nLbl = QtWidgets.QLabel(self.tab_2)
        self.nLbl.setGeometry(QtCore.QRect(550, 430, 141, 16))
        self.nLbl.setText("")
        self.nLbl.setObjectName("nLbl")
        self.encPrivatLbl = QtWidgets.QLabel(self.tab_2)
        self.encPrivatLbl.setGeometry(QtCore.QRect(550, 460, 141, 16))
        self.encPrivatLbl.setText("")
        self.encPrivatLbl.setObjectName("encPrivatLbl")
        self.encRename = QtWidgets.QLineEdit(self.tab_2)
        self.encRename.setGeometry(QtCore.QRect(290, 460, 141, 22))
        self.encRename.setObjectName("encRename")
        self.encProses = QtWidgets.QLabel(self.tab_2)
        self.encProses.setGeometry(QtCore.QRect(230, 510, 91, 16))
        self.encProses.setText("")
        self.encProses.setObjectName("encProses")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.decGraphicsView = QtWidgets.QGraphicsView(self.tab_3)
        self.decGraphicsView.setGeometry(QtCore.QRect(10, 10, 421, 371))
        self.decGraphicsView.setObjectName("decGraphicsView")
        self.decGraphicsView2 = QtWidgets.QGraphicsView(self.tab_3)
        self.decGraphicsView2.setGeometry(QtCore.QRect(450, 10, 421, 371))
        self.decGraphicsView2.setObjectName("decGraphicsView2")
        self.decOpenBtn = QtWidgets.QPushButton(self.tab_3)
        self.decOpenBtn.setGeometry(QtCore.QRect(10, 400, 93, 28))
        self.decOpenBtn.setObjectName("decOpenBtn")
        self.decKeyPlayfair = QtWidgets.QLineEdit(self.tab_3)
        self.decKeyPlayfair.setGeometry(QtCore.QRect(130, 400, 301, 21))
        self.decKeyPlayfair.setObjectName("decKeyPlayfair")
        self.decNLE = QtWidgets.QLineEdit(self.tab_3)
        self.decNLE.setGeometry(QtCore.QRect(130, 430, 141, 22))
        self.decNLE.setText("")
        self.decNLE.setObjectName("decNLE")
        self.decPrivateLE = QtWidgets.QLineEdit(self.tab_3)
        self.decPrivateLE.setGeometry(QtCore.QRect(290, 430, 141, 22))
        self.decPrivateLE.setObjectName("decPrivateLE")
        self.decBtn = QtWidgets.QPushButton(self.tab_3)
        self.decBtn.setGeometry(QtCore.QRect(130, 500, 93, 28))
        self.decBtn.setObjectName("decBtn")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(460, 400, 81, 16))
        self.label_5.setObjectName("label_5")
        self.decTimeLbl = QtWidgets.QLabel(self.tab_3)
        self.decTimeLbl.setGeometry(QtCore.QRect(550, 400, 47, 13))
        self.decTimeLbl.setText("")
        self.decTimeLbl.setObjectName("decTimeLbl")
        self.decRename = QtWidgets.QLineEdit(self.tab_3)
        self.decRename.setGeometry(QtCore.QRect(130, 460, 141, 22))
        self.decRename.setText("")
        self.decRename.setObjectName("decRename")
        self.decProses = QtWidgets.QLabel(self.tab_3)
        self.decProses.setGeometry(QtCore.QRect(230, 510, 91, 16))
        self.decProses.setText("")
        self.decProses.setObjectName("decProses")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.ujiGraphicsView = QtWidgets.QGraphicsView(self.tab_4)
        self.ujiGraphicsView.setGeometry(QtCore.QRect(10, 10, 421, 371))
        self.ujiGraphicsView.setObjectName("ujiGraphicsView")
        self.ujiGraphicsView2 = QtWidgets.QGraphicsView(self.tab_4)
        self.ujiGraphicsView2.setGeometry(QtCore.QRect(450, 10, 421, 371))
        self.ujiGraphicsView2.setObjectName("ujiGraphicsView2")
        self.ujiOpenBtn = QtWidgets.QPushButton(self.tab_4)
        self.ujiOpenBtn.setGeometry(QtCore.QRect(10, 390, 93, 28))
        self.ujiOpenBtn.setObjectName("ujiOpenBtn")
        self.ujiOpenBtn2 = QtWidgets.QPushButton(self.tab_4)
        self.ujiOpenBtn2.setGeometry(QtCore.QRect(450, 390, 93, 28))
        self.ujiOpenBtn2.setObjectName("ujiOpenBtn2")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(460, 430, 55, 16))
        self.label_4.setObjectName("label_4")
        self.ujiNcBtn = QtWidgets.QPushButton(self.tab_4)
        self.ujiNcBtn.setGeometry(QtCore.QRect(10, 430, 93, 28))
        self.ujiNcBtn.setObjectName("ujiNcBtn")
        self.ncLbl = QtWidgets.QLabel(self.tab_4)
        self.ncLbl.setGeometry(QtCore.QRect(520, 470, 55, 16))
        self.ncLbl.setText("")
        self.ncLbl.setObjectName("ncLbl")
        self.ujiLbl = QtWidgets.QLabel(self.tab_4)
        self.ujiLbl.setGeometry(QtCore.QRect(530, 430, 81, 16))
        self.ujiLbl.setText("")
        self.ujiLbl.setObjectName("ujiLbl")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.entropyGraphicsView = QtWidgets.QGraphicsView(self.tab_5)
        self.entropyGraphicsView.setGeometry(QtCore.QRect(30, 30, 421, 371))
        self.entropyGraphicsView.setObjectName("entropyGraphicsView")
        self.entOpenBtn = QtWidgets.QPushButton(self.tab_5)
        self.entOpenBtn.setGeometry(QtCore.QRect(470, 30, 93, 28))
        self.entOpenBtn.setObjectName("entOpenBtn")
        self.entBtn = QtWidgets.QPushButton(self.tab_5)
        self.entBtn.setGeometry(QtCore.QRect(470, 80, 93, 28))
        self.entBtn.setObjectName("entBtn")
        self.entPathLbl = QtWidgets.QLabel(self.tab_5)
        self.entPathLbl.setGeometry(QtCore.QRect(580, 40, 281, 16))
        self.entPathLbl.setText("")
        self.entPathLbl.setObjectName("entPathLbl")
        self.entLbl = QtWidgets.QLabel(self.tab_5)
        self.entLbl.setGeometry(QtCore.QRect(660, 90, 161, 16))
        self.entLbl.setText("")
        self.entLbl.setObjectName("entLbl")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(580, 90, 71, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 260, 881, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.photo = QtWidgets.QLabel(self.tab)
        self.photo.setGeometry(QtCore.QRect(290, 20, 291, 241))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("undip.png"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # ==================================================
        # open image encription
        self.encOpenBtn.clicked.connect(lambda: self.showDialog(1))
        # encryp button
        self.encBtn.clicked.connect(self.encClick)
        # open image decryption
        self.decOpenBtn.clicked.connect(lambda: self.showDialog(2))
        # decryp button
        self.decBtn.clicked.connect(self.decClick)
        # open uji NC
        self.ujiOpenBtn.clicked.connect(lambda: self.showDialog(3))
        self.ujiOpenBtn2.clicked.connect(lambda: self.showDialog(4))
        # hitung uji NC
        self.ujiNcBtn.clicked.connect(self.ncClick)
        # open entropi
        self.entOpenBtn.clicked.connect(lambda: self.showDialog(5))
        #
        self.entBtn.clicked.connect(self.entClick)
        # ==================================================

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # function==============================================

    def showDialog(self, a):
        fileName = QFileDialog.getOpenFileName(self, 'Open File', '')[0]
        self.scene = QGraphicsScene()
        self.scene.addPixmap(QPixmap(fileName))
        global fileNamePath
        global fileNamePath2
        global fileNamePath3
        if a == 1:
            self.encGraphicsView.setScene(self.scene)
            fileNamePath = fileName
        if a == 2:
            self.decGraphicsView.setScene(self.scene)
            fileNamePath = fileName
        if a == 3:
            self.ujiGraphicsView.setScene(self.scene)
            fileNamePath = fileName
        if a == 4:
            self.ujiGraphicsView2.setScene(self.scene)
            fileNamePath2 = fileName
        if a == 5:
            self.entropyGraphicsView.setScene(self.scene)
            fileNamePath3 = fileName
            self.entPathLbl.setText(str(fileNamePath3))

    def encClick(self):
        kp = self.encKeyPlayfair.text()
        p = self.encPrimeLE1.text()
        q = self.encPrimeLE2.text()
        e = self.encKeyPublic.text()
        rename = self.encRename.text()

        b = len(kp) != 0  # kunci playfair
        c = (len(p) != 0) and (len(q) != 0) and (len(e) != 0)
        re = len(rename) != 0

        if (c == True and b == True and re == True):  # semua field tidak kosong
            if ((isPrime(p) and isPrime(q) and isPrime(e)) == True):  # cek prima
                a = int(p) * int(q)
                if (a > 254 and a < 65535):

                    self.encProses.setText('proses....')
                    d, n, t, fileEnc = finalEncmix(
                        fileNamePath, kp, int(p), int(q), int(e), rename)

                    self.encTimeLbl.setText(str(t)+' s')
                    self.nLbl.setText(str(n))
                    self.encPrivatLbl.setText(str(d))
                    self.scene = QGraphicsScene()
                    self.scene.addPixmap(QPixmap(fileEnc))
                    self.encGraphicsView2.setScene(self.scene)
                    self.encProses.setText('')

                else:
                    msg = QMessageBox()
                    msg.setWindowTitle("Error!!!")
                    msg.setText(
                        "p*q = %s pastikan p*q > 255 & p*q < 65535!!!" % str(a))
                    msg.setIcon(QMessageBox.Critical)
                    x = msg.exec_()
            else:
                msg = QMessageBox()
                msg.setWindowTitle("Error!!!")
                msg.setText("Pastikan nilai p, q, dan e bilangan prima!!!")
                msg.setIcon(QMessageBox.Critical)
                x = msg.exec_()
        else:
            print("x")
            msg = QMessageBox()
            msg.setWindowTitle("Error!!!")
            msg.setText("Pastikan semua field terisi!!!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

    def decClick(self):
        kp = self.decKeyPlayfair.text()
        n = self.decNLE.text()
        d = self.decPrivateLE.text()
        rename = self.decRename.text()

        b = len(kp) != 0  # kunci playfair
        c = (len(n) != 0) and (len(d) != 0)
        re = len(rename) != 0

        if(b == True and c == True and re == True):
            if(int(n) > 254):
                # self.decProses("proses...")
                t, fileDec = finalDecmix(
                    fileNamePath, kp, int(d), int(n), rename)
                self.decTimeLbl.setText(str(t)+' s')
                self.scene = QGraphicsScene()
                self.scene.addPixmap(QPixmap(fileDec))
                self.decGraphicsView2.setScene(self.scene)
                # self.decproses("selesai...")
            else:
                msg = QMessageBox()
                msg.setWindowTitle("Error!!!")
                msg.setText("pastikan nilai n > 254!!!")
                msg.setIcon(QMessageBox.Critical)
                x = msg.exec_()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error!!!")
            msg.setText("pastikan semua field terisi!!!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

    def ncClick(self):
        if(len(fileNamePath) != 0 and len(fileNamePath2) != 0):
            nc = NC(fileNamePath, fileNamePath2)
            print(nc)
            self.ujiLbl.setText(str(nc)+' s')
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error!!!")
            msg.setText("pastikan telah memilih 2 citra!!!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

    def entClick(self):
        if(len(fileNamePath3) != 0):
            ent = Entropy(fileNamePath3)
            self.entLbl.setText(str(ent))
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Error!!!")
            msg.setText("pastikan telah citra!!!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

        # ======================================================

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UI"))
        MainWindow.setWindowIcon(QtGui.QIcon("icon.png"))
        self.encOpenBtn.setText(_translate("MainWindow", "Pilih Gambar"))
        self.encKeyPlayfair.setPlaceholderText(
            _translate("MainWindow", "kunci playfair"))
        self.encPrimeLE1.setPlaceholderText(
            _translate("MainWindow", "bilangan prima ke-1"))
        self.encPrimeLE2.setPlaceholderText(
            _translate("MainWindow", "bilangan prima ke-2"))
        self.label.setText(_translate("MainWindow", "Waktu         :"))
        self.encKeyPublic.setPlaceholderText(
            _translate("MainWindow", "kunci publik"))
        self.label_2.setText(_translate("MainWindow", "n                 :"))
        self.label_3.setText(_translate("MainWindow", "Kunci Privat  :"))
        self.encBtn.setText(_translate("MainWindow", "Enkripsi"))
        self.encRename.setPlaceholderText(
            _translate("MainWindow", "nama file enkripsi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_2), _translate("MainWindow", "Enkripsi"))
        self.decOpenBtn.setText(_translate("MainWindow", "Pilih Gambar"))
        self.decKeyPlayfair.setPlaceholderText(
            _translate("MainWindow", "kunci playfair"))
        self.decNLE.setPlaceholderText(_translate("MainWindow", "nilai n"))
        self.decPrivateLE.setPlaceholderText(
            _translate("MainWindow", "kunci privat"))
        self.decBtn.setText(_translate("MainWindow", "Dekripsi"))
        self.label_5.setText(_translate("MainWindow", "Waktu          :"))
        self.decRename.setPlaceholderText(
            _translate("MainWindow", "nama file dekripsi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_3), _translate("MainWindow", "Dekripsi"))
        self.ujiOpenBtn.setText(_translate("MainWindow", "Pilih Gambar"))
        self.ujiOpenBtn2.setText(_translate("MainWindow", "Pilih Gambar"))
        self.label_4.setText(_translate("MainWindow", "Nilai NC    :"))
        self.ujiNcBtn.setText(_translate("MainWindow", "Hitung"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_4), _translate("MainWindow", "Uji Kesamaan Citra"))
        self.entOpenBtn.setText(
            _translate("MainWindow", "Pilih Gambar"))
        self.entBtn.setText(_translate("MainWindow", "Hitung"))
        self.label_6.setText(_translate("MainWindow", "Nilai Entropy :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_5), _translate("MainWindow", "Hitung Entropy"))
        self.label_7.setText(_translate("MainWindow", "Nama      : Mukhammad Rizky Sobirin\n"
                                        "Nim         : 24060117120012 \n"
                                        "Dekripsi   : Aplikasi ini digunakan sebagai implementasi dalam pengujian tugas akhir dengan \n"
                                        "                 judul KRIPTOGRAFI CITRA MENGGUNAKAN METODE PLAYFAIR MODIFIKASI DAN RSA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab), _translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
